### ISSUE TITLE
Card services error

### ISSUE THREAD

**Issue by D4v1d98Ru1z** [OdontologyTeam/Landing-Page#5]
La caja que trae el botón ocupa demasiado espacio tanto así que ocupa espacio. Adjunto una imagen para identificar el error. El problema se da en responsive.
![screenshot from 2018-11-24 16-01-34](https://user-images.githubusercontent.com/21083108/48972970-81ea8a80-f003-11e8-9311-fc9d5b35d3ad.png)

**Comment by teamzz111** [comment]
Mmmmm podría indicarme su resolución exacta, no tengo problemas en esta parte.

![image](https://user-images.githubusercontent.com/37392536/49053355-d0438900-f1bd-11e8-952d-bcb6e0c75f52.png)

**Comment by teamzz111** [comment]
Solucionado, puede verlo en

[https://github.com/OdontologyTeam/Landing-Page/commit/ae5b3e7050b8b5bb75b395468dfe050eed38c5af](url)
